# Generated by Django 2.1.7 on 2019-03-13 08:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(10000)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(choices=[('J', 'Janitor'), ('C', 'Chef'), ('S', 'Secretary'), ('CEO', 'Chief Executive Officer'), ('VP', 'Vice President'), ('D', 'Developer'), ('PM', 'Project Manager'), ('JD', 'Junior Developer'), ('HR', 'Human Resources Representative'), ('M', 'Marketer'), ('S', 'Salesperson'), ('QAE', 'Quality Assurance Engineer')], max_length=3)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp.Employee')),
            ],
        ),
    ]
